version: "3.3"

services:

  bun-fetch:
    container_name: "bun-fetch"
    image: "ghcr.io/kubero-dev/buildpacks/fetch:main"
    environment:
      - GIT_REPOSITORY=${GIT_REPOSITORY:-git@github.com:kubero-dev/template-nodeapp.git}
      - GIT_BRANCH=${GIT_BRANCH:-main}
      - KUBERO_BUILDPACK_DEFAULT_BUILD_CMD="bun install"
      - KUBERO_BUILDPACK_DEFAULT_RUN_CMD="bun index.js"
    volumes:
      - ../../data:/app
      - ../../keys/deploykey:/root/.ssh/deploykey

  bun-build:
    container_name: "bun-build"
    image: oven/bun:latest
    working_dir: /app
    #command: tail -f /dev/null
    command: './init-build.sh'
    volumes:
      - ../../data:/app
    depends_on:
      bun-fetch:
        condition: service_completed_successfully


  bun-run:
    container_name: "bun-run"
    image: oven/bun:latest
    working_dir: /app
    #command: tail -f /dev/null
    command: './init-web.sh'
    environment:
      - PORT=9999
    volumes:
      - ../../data:/app:ro
    ports:
      - "8001:9999"
    depends_on:
      bun-build:
        condition: service_completed_successfully